[build]
builder = "nixpacks"

[deploy]
startCommand = "cd /app && uvicorn main:app --host 0.0.0.0 --port=${PORT}"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv", "ffmpeg", "espeak-ng"]
aptPkgs = ["python3-venv"]

[phases.install]
cmds = [
  "pwd",
  "ls -la",
  "mkdir -p /app",
  "cp -r . /app/",
  "cd /app",
  "ls -la",
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[phases.setup.env]
PYTHONPATH = "/app"
PATH = "/opt/venv/bin:${PATH}"
