[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[nixpacks]
install-cmd = """
apt-get update && \
apt-get install -y \
    build-essential \
    python3-dev \
    ffmpeg \
    pkg-config \
    gcc \
    g++ \
    gfortran \
    git && \
pip install --no-cache-dir wheel setuptools Cython && \
pip install --no-cache-dir numpy==1.24.3 && \
pip install --no-cache-dir -r requirements.txt
"""
