[build]
builder = "docker"
dockerfilePath = "Dockerfile"
buildContext = "."  # Explicitly set build context to current directory

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
