[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[nixpacks]
python_version = "3.11"
providers = ["python", "nodejs"]

[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "python311Packages.setuptools",
    "python311Packages.wheel",
    "python311Packages.distutils-extra",
    "python311Packages.python-distutils-extra",
    "gcc",
    "gfortran",
    "ffmpeg",
    "pkg-config"
]

[phases.install]
cmds = [
    "apt-get update && apt-get install -y python3.11-distutils python3-distutils",
    "python -m pip install --upgrade pip setuptools wheel",
    "pip install numpy==1.24.3",
    "pip install -r requirements.txt"
]
