[build]
builder = "nixpacks"

[deploy]
startCommand = "cd /app && uvicorn main:app --host 0.0.0.0 --port=${PORT}"

[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "python311Packages.virtualenv",
    "ffmpeg",
    "espeak-ng",
    "glib",
    "pkg-config",
    "SDL2",
    "SDL2_mixer"
]
aptPkgs = [
    "python3-venv",
    "libglib2.0-0",
    "libglib2.0-dev",
    "libsdl2-2.0-0",
    "libsdl2-mixer-2.0-0",
    "libsdl2-dev",
    "libsdl2-mixer-dev",
    "libasound2-dev",
    "libportaudio2",
    "libportaudiocpp0",
    "portaudio19-dev",
    "ffmpeg"
]

[phases.setup.env]
SDL_AUDIODRIVER = "disk"
PYTHONPATH = "/app"
PATH = "/opt/venv/bin:${PATH}"

[phases.install]
cmds = [
  "pwd",
  "ls -la",
  "mkdir -p /app",
  "cp -r . /app/",
  "cd /app",
  "ls -la",
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]
