[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[nixpacks]
python_version = "3.11.7"

[phases.setup]
nixPkgs = ["python311", "gcc", "gfortran", "ffmpeg", "pkg-config"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "pip install wheel setuptools Cython",
    "pip install -r requirements.txt"
]
