[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100

[variables]
PYTHON_VERSION = "3.11"
NIXPACKS_PYTHON_VERSION = "3.11"
PATH = "/nix/var/nix/profiles/default/bin:$PATH"
LD_LIBRARY_PATH = "/nix/var/nix/profiles/default/lib:/nix/var/nix/profiles/default/lib64:$LD_LIBRARY_PATH"
PYTHONPATH = "/nix/var/nix/profiles/default/lib/python3.11/site-packages:$PYTHONPATH"
SDL_AUDIODRIVER = "dummy"
AUDIODEV = "null"
FFMPEG_PATH = "/nix/var/nix/profiles/default/bin/ffmpeg"

[phases.setup]
nixPkgs = [
    "ffmpeg",
    "glib",
    "glib.dev",
    "pkg-config",
    "gcc",
    "python311",
    "python311Packages.pygame",
    "sdl2",
    "sdl2_mixer",
    "alsa-lib",
    "alsa-utils",
    "pulseaudio"
]

[phases.build]
cmds = [
    "mkdir -p /tmp/tts_cache && chmod 777 /tmp/tts_cache",
    "ldconfig || true"
]
